name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache client node modules
      uses: actions/cache@v4
      with:
        path: client/node_modules
        key: client-node-modules-${{ hashFiles('client/package-lock.json') }}

    - name: Cache server node modules
      uses: actions/cache@v4
      with:
        path: server/node_modules
        key: server-node-modules-${{ hashFiles('server/package-lock.json') }}

    - name: Client - Install dependencies
      working-directory: ./client
      run: npm ci

    - name: Client - Lint and format check
      working-directory: ./client
      run: |
        npm run lint
        npm run format:check
        
    - name: Client - Build
      working-directory: ./client
      run: npm run build

    - name: Server - Install dependencies
      working-directory: ./server
      run: npm ci --legacy-peer-deps

    - name: Server - Lint and format check
      working-directory: ./server
      run: |
        npm run lint
        npm run format:check

    - name: Server - Build
      working-directory: ./server
      run: npm run build

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend Docker image
      run: |
        docker build -f server/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-game-backend:latest ./server

    - name: Build frontend Docker image
      run: |
        docker build -f client/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-game-frontend:latest ./client

    - name: Push backend Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-game-backend:latest

    - name: Push frontend Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-game-frontend:latest
